try{
    hello();
} catch (error){
    console.log(error);
}

try{
    hello1();
} catch {
    console.log('error personalizado');
}

